### ISSUE TITLE
Demo site / Screenshot

### ISSUE THREAD

**Issue by wolfika** [m1guelpf/support_center#15]
Seems like a nice project! 👍 
Would be great if you could create a demo website where people can try the app before getting too much involved in setting it up, or at least include a set of screenshots in the readme. Thanks!

**Comment by m1guelpf** [comment]
@wolfika I will post screenshots this afternoon.

**Comment by m1guelpf** [comment]
@wolfika @jpuck I've uploaded a video!
https://youtu.be/huFLWRFBlg4
